# This is a basic workflow to help you get started with Actions

name: Deployment angular to Heroku

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the releases branch
  push:
    branches: 
      - deploy
  # pull_request:
    # branches: [ releases ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.0.0
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "semwee"
          heroku_email: alfrednicotsu@gmail.com
          usedocker: true