# This is a basic workflow to help you get started with Actions

name: Deployment angular to Heroku

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the releases branch
  push:
    branches: 
      - deploy

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Updating Ubuntu system and Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: sudo apt update && sudo apt install heroku neofetch
      - name: Checking the info
        run: neofetch

      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: alfrednicotsu@gmail.com
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: semwee
          branch: HEAD
          useforce: false
          dynamicFiles: false

